# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IP7bqmruCaoxffQlGYBFgOzY0IQyc_2_
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
df = pd.read_csv('sales_data.csv')
print(df);

df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
print(df);

top_products = df.groupby('Product')['Sales'].sum()
print(top_products);

import matplotlib.pyplot as plt
plt.bar(top_products.index , top_products.values)
plt.show()

df.head()

df.tail()

df.info()

import matplotlib.pyplot as plt
product_names=df['Product']
revenues=df['Sales']
plt.pie(revenues , labels=product_names )
plt.show()

df['Order Date']=pd.to_datetime(df['Order Date'])
df['Month']=df['Order Date'].dt.month_name()
monthly_data=df.groupby('Month')['Sales'].sum()
plt.plot(monthly_data.index, monthly_data.values)
plt.show()